name: resources_package
description: "aryan front resources"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.1
  localization: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: IRANSansX
      fonts:
        - asset: assets/fonts/IRANSansX-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Semibold.ttf
          weight: 600
    - family: IRANSansRegular
      fonts:
        - asset: assets/fonts/IRANSansX-Regular.ttf
          weight: 600
    - family: Yekan
      fonts:
        - asset: assets/fonts/Yekan.ttf
          weight: 600
  assets:
    - assets/images/account.png
    - assets/images/activeaccount.png
    - assets/images/defaults.png
    - assets/images/activedefaults.png
    - assets/images/menu.png
    - assets/images/activemenu.png
    - assets/images/new.png
    - assets/images/activenew.png
    - assets/images/opened.png
    - assets/images/activeopened.png
    - assets/images/userinfo.png
    - assets/images/user_devices.png
    - assets/images/user_sign_out.png
    - assets/images/user_title.png
    - assets/images/user_other_accounts.png
    - assets/images/user_settings.png
    - assets/images/user_wallet.png
    - assets/images/user_password_change.png
    - assets/images/sort.png
    - assets/images/filternone.png
    - assets/images/filtersigning.png
    - assets/images/refresh.png
    - assets/images/futures.png
    - assets/images/more.png
    - assets/images/pagination_right.png
    - assets/images/pagination_left.png
    - assets/images/add.png
    - assets/images/aryan_app.png
    - assets/images/lang_icon.png
    - assets/images/eyes_close.png
    - assets/images/eyes_open.png

  generate: true
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
